// <auto-generated />
using FiskAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FiskAPI.Migrations
{
    [DbContext(typeof(FiskContext))]
    partial class FiskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FiskAPI.Models.Fisk", b =>
                {
                    b.Property<int>("FiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Art")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fakta")
                        .HasColumnType("TEXT");

                    b.HasKey("FiskId");

                    b.ToTable("Fisks");
                });
#pragma warning restore 612, 618
        }
    }
}
